name : CI

on:
        push:
                branches: [ main, master ]
        pull_request:
                branches: [ main, master ]

jobs:
        build-and-test:
                runs-on: ubuntu-latest

                steps:
                        - name : Checkout code
                          uses : actions/checkout@v4
                          with : 
                                submodules : recursive

                        - name : Install dependencies
                          run  : |
                               sudo apt-get update
                               sudo apt-get install -y cmake build-essential

                        - name : Clone Google test
                          run  : |
                                git clone https://github.com/google/googletest.git

                        - name : Configure CMake
                          run  : |
                                mkdir build
                                cd build
                                cmake ..

                        - name : Build
                          run  : | 
                                cd build
                                make

                        - name : Run tests
                          run  : |
                                cd build
                                ./asm_tests
